Nhdd mappings
moh-kenya/echis-2.0-integration pull request #114
Opened 2023-09-06 07:16 UTC by Justus446

2023-09-06 08:46 UTC, karimkkanji commented
Resolve the conflict then restore the keys as they are required when the key is found when sent by echis in the payload of the screening object.

2023-09-06 09:00 UTC, karimkkanji commented
Once done, this should close #110

2023-09-06 11:33 UTC, freddieptf requested changes
Great effort @Justus446, we just need to confirm that we have the mappings in this [document](https://docs.google.com/document/d/147EpDeTUrh3u5CokxQRLcMAh30jlVRxc0ZH-ro11ivo/edit#heading=h.q4vzhc7zk1fe). Let's make sure we didn't comment out mappings that we need as well

2023-09-06 11:33 UTC, freddieptf commented on src/utils/referral.js
> +  // feeling_of_worthlessness: {
This is required for [PNC Mother](https://github.com/moh-kenya/config-echis-2.0/blob/main/forms/app/postnatal_care_service.xlsx), i believe it's part of mental danger signs. Some of the mappings commented out might actually be needed

2023-09-11 05:10 UTC, Justus446 commented
As agreed upon last Friday.Some tickets have mappings that need an expert (There no one to one mapping of the eCHIS symptoms to NHDD codes).Also there's previous work done by the design team that does not match to the codes in NHDD. [Link to the doc](https://docs.google.com/spreadsheets/d/1cowY7uIR7bMCHTVQV8YxcRRolAYTy-Zd/edit#gid=1081183559)
@kitsao , Kindly reassign the ticket.

2023-10-06 09:45 UTC, closed without merging

2023-10-06 09:45 UTC, freddieptf commented
Closing this, worked on in #119 #115