add treatment follow up nhdd code mappings
moh-kenya/echis-2.0-integration pull request #119
Opened 2023-09-21 00:04 UTC by freddieptf

Part of https://github.com/moh-kenya/echis-2.0-integration/issues/110

2023-09-26 12:00 UTC, kitsao requested changes
Good progress @freddieptf. It will be there in no time. I have shared a few comments inline.

2023-09-26 19:38 UTC, freddieptf commented on src/utils/nhdd_mappings.js
> +        display: "Deterioration",
They are all strings regardless

2023-09-26 19:48 UTC, freddieptf commented on src/utils/nhdd_mappings.js
> +};
Yes but we'd need to review the current forms and make sure the diagnosis labels we include in the screening object are the same globally

2023-09-26 21:21 UTC, freddieptf commented on src/utils/nhdd_mappings.js
> +};
> Can use a function for this? It shouldn't be complicated, right?

What did you have in mind?

2023-09-28 06:38 UTC, kitsao commented on src/utils/nhdd_mappings.js
> +        display: "Deterioration",
Yeah, but remember we set the rules, we stick to them.

2023-09-28 07:52 UTC, kitsao approved these changes
As discussed @freddieptf, lets refactor later, complete with tests. UAT already passed.

2023-09-28 09:19 UTC, merged